name: on_process_button_widget
description: An awesome button widget that fulfills all your demands in Button. Operation animation, status, and many more.
version: 2.0.7
homepage: https://github.com/SHAJED99/on_process_button_widget
license: BSD 3-Clause

screenshots:
  - description: 'Example of on_process_button_widget'
    path: screenshots/all.gif

topics:
  - button
  - elevated-button
  - animated-button

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
